/**
 * @file Globals.h
 * @author TjGer22
 * @brief Global compile-time constants, firmware version and JSON config keys.
 * @date 2026
 *
 * @details
 * Defines the firmware version string, hardware pin assignments,
 * default network parameters and the string keys used in the JSON
 * configuration file. Included by virtually every translation unit.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

//As long as there is a 0 here, the software is in test mode.
//If this becomes 1 then the software works as intended
#define release_mode 1

#define Firmwareversion "2.0.0"

/**
 * Configuration file JSON keys
*/
#define CONF_DEVICE_SERIAL "CONF_DEVICE_SERIAL"
#define CONF_WIFI_SERVER_PASSWORD "CONF_WIFI_SERVER_PASSWORD"
#define CONF_WIFI_CLIENT_SSID "CONF_WIFI_CLIENT_SSID"
#define CONF_WIFI_CLIENT_PASSWORD "CONF_WIFI_CLIENT_PASSWORD"
#define CONF_WIFI_MODE "CONF_WIFI_MODE"
#define CONF_DEVICE_TYPE "CONF_DEVICE_TYPE"
#define CONF_DEVICE_LANDINGPAGE "CONF_DEVICE_LANDINGPAGE"
#define CONF_DEVICE_Coefficient6 "CONF_DEVICE_Coefficient6"
#define CONF_DEVICE_Coefficient5 "CONF_DEVICE_Coefficient5"
#define CONF_DEVICE_Coefficient4 "CONF_DEVICE_Coefficient4"
#define CONF_DEVICE_Coefficient3 "CONF_DEVICE_Coefficient3"
#define CONF_DEVICE_Coefficient2 "CONF_DEVICE_Coefficient2"
#define CONF_DEVICE_Coefficient1 "CONF_DEVICE_Coefficient1"
#define CONF_DEVICE_Coefficient0 "CONF_DEVICE_Coefficient0"
#define CONF_DEVICE_GYROOFFSETZ "CONF_DEVICE_GYROOFFSETZ"
#define CONF_DEVICE_GYROOFFSETY "CONF_DEVICE_GYROOFFSETY"
#define CONF_DEVICE_GYROOFFSETX "CONF_DEVICE_GYROOFFSETX"
#define CONF_DEVICE_ACCELOFFSETZ "CONF_DEVICE_ACCELOFFSETZ"
#define CONF_DEVICE_ACCELOFFSETY "CONF_DEVICE_ACCELOFFSETY"
#define CONF_DEVICE_ACCELOFFSETX "CONF_DEVICE_ACCELOFFSETX"
#define CONF_BLUETOOTH_ENABLE "CONF_BLUETOOTH_ENABLE"
#define CONF_BLUETOOTH_UUID "CONF_BLUETOOTH_UUID"
#define CONF_BLUETOOTH_BLETRANSPOWER "CONF_BLUETOOTH_BLETRANSPOWER"
#define CONF_BREWBLOX_ENABLED "CONF_BREWBLOX_ENABLED"
#define CONF_BREWBLOX_SERVER "CONF_BREWBLOX_SERVER"
#define CONF_BREWBLOX_PORT "CONF_BREWBLOX_PORT"
#define CONF_BREWBLOX_TOPIC "CONF_BREWBLOX_TOPIC"
#define CONF_BREWBLOX_NAME "CONF_BREWBLOX_NAME"
#define CONF_BREWFATHER_ENABLED "CONF_BREWFATHER_ENABLED"
#define CONF_BREWFATHER_URL "CONF_BREWFATHER_URL"
#define CONF_BIERBOT_ENABLED "CONF_BIERBOT_ENABLED"
#define CONF_BIERBOT_TOKEN "CONF_BIERBOT_TOKEN"
#define CONF_CRAFTBEERPI_ENABLED "CONF_CRAFTBEERPI_ENABLED"
#define CONF_CRAFTBEERPI_SERVER "CONF_CRAFTBEERPI_SERVER"
#define CONF_FHEM_ENABLED "CONF_FHEM_ENABLED"
#define CONF_FHEM_SERVER "CONF_FHEM_SERVER"
#define CONF_FHEM_PORT "CONF_FHEM_PORT"
#define CONF_FHEM_NAME "CONF_FHEM_NAME"
#define CONF_GRAINFATHER_ENABLED "CONF_GRAINFATHER_ENABLED"
#define CONF_GRAINFATHER_URL "CONF_GRAINFATHER_URL"
#define CONF_HTTP_ENABLED "CONF_HTTP_ENABLED"
#define CONF_HTTP_SERVER "CONF_HTTP_SERVER"
#define CONF_HTTP_URL "CONF_HTTP_URL"
#define CONF_HTTP_PORT "CONF_HTTP_PORT"
#define CONF_INFLUXDB_ENABLE "CONF_INFLUXDB_ENABLE"
#define CONF_INFLUXDB_SERVER "CONF_INFLUXDB_SERVER"
#define CONF_INFLUXDB_PORT "CONF_INFLUXDB_PORT"
#define CONF_INFLUXDB_DB "CONF_INFLUXDB_DB"
#define CONF_INFLUXDB_NAME "CONF_INFLUXDB_NAME"
#define CONF_INFLUXDB_USER "CONF_INFLUXDB_USER"
#define CONF_INFLUXDB_PASSWORT "CONF_INFLUXDB_PASSWORT"
#define CONF_INFLUXDB_MEASUREMENTNAME "CONF_INFLUXDB_MEASUREMENTNAME"
#define CONF_MQTT_ENABLE "CONF_MQTT_ENABLE"
#define CONF_MQTT_SERVER "CONF_MQTT_SERVER"
#define CONF_MQTT_PORT "CONF_MQTT_PORT"
#define CONF_MQTT_USER "CONF_MQTT_USER"
#define CONF_MQTT_PASSWORT "CONF_MQTT_PASSWORT"
#define CONF_MQTT_NAME "CONF_MQTT_NAME"
#define CONF_MQTT_TOPICLEVEL "CONF_MQTT_TOPICLEVEL"
#define CONF_PROMETHEUS_ENABLE "CONF_PROMETHEUS_ENABLE"
#define CONF_PROMETHEUS_SERVER "CONF_PROMETHEUS_SERVER"
#define CONF_PROMETHEUS_PORT "CONF_PROMETHEUS_PORT"
#define CONF_PROMETHEUS_JOB "CONF_PROMETHEUS_JOB"
#define CONF_PROMETHEUS_INSTANCE "CONF_PROMETHEUS_INSTANCE"
#define CONF_TCONTROL_ENABLE "CONF_TCONTROL_ENABLE"
#define CONF_TCONTROL_SERVER "CONF_TCONTROL_SERVER"
#define CONF_TCONTROL_PORT "CONF_TCONTROL_PORT"
#define CONF_TCP_ENABLE "CONF_TCP_ENABLE"
#define CONF_TCP_SERVER "CONF_TCP_SERVER"
#define CONF_TCP_PORT "CONF_TCP_PORT"
#define CONF_TELEGRAM_ENABLE "CONF_TELEGRAM_ENABLE"
#define CONF_TELEGRAM_TOKEN "CONF_TELEGRAM_TOKEN"
#define CONF_TELEGRAM_CHAT_ID "CONF_TELEGRAM_CHAT_ID"
#define CONF_THINGSPEAK_ENABLE "CONF_THINGSPEAK_ENABLE"
#define CONF_THINGSPEAK_TOKEN "CONF_THINGSPEAK_TOKEN"
#define CONF_THINGSPEAK_CHANNEL "CONF_THINGSPEAK_CHANNEL"
#define CONF_UBIDOTS_ENABLE "CONF_UBIDOTS_ENABLE"
#define CONF_UBIDOTS_TOKEN "CONF_UBIDOTS_TOKEN"
#define CONF_UBIDOTS_NAME "CONF_UBIDOTS_NAME"
#define CONF_GOOGLESHEETS_ENABLE "CONF_GOOGLESHEETS_ENABLE"
#define CONF_GOOGLESHEETS_TOKEN "CONF_GOOGLESHEETS_TOKEN"
#define CONF_GOOGLESHEETS_NAME "CONF_GOOGLESHEETS_NAME"
#define CONF_PLAINWATER_YAR "CONF_PLAINWATER_YAR"
#define CONF_PLAINWATER_PITCH "CONF_PLAINWATER_PITCH"
#define CONF_PLAINWATER_ROLL "CONF_PLAINWATER_ROLL"


#define CONF_DEEPSLEEP_ENABLE "CONF_DEEPSLEEP_ENABLE"
#define CONF_DEEPSLEEP_SECONDS "CONF_DEEPSLEEP_SECONDS"
#define CONF_DEEPSLEEP_MINUTES "CONF_DEEPSLEEP_MINUTES"
#define CONF_DEEPSLEEP_HOURS "CONF_DEEPSLEEP_HOURS"
#define CONF_TEMPCOMPENSATION_ENABLED "CONF_TEMPCOMPENSATION_ENABLED"
#define CONF_TEMPCOMPENSATION_FACTOR "CONF_TEMPCOMPENSATION_FACTOR"
#define CONF_RECHEADSTAND_ENABLED "CONF_RECHEADSTAND_ENABLED"
#define CONF_AUTOFIRMWAREUPDATE_ENABLED "CONF_AUTOFIRMWAREUPDATE_ENABLED"
#define CONF_TEMPERATURE_UNIT "CONF_TEMPERATURE_UNIT"
#define CONF_TILT_UNIT "CONF_TILT_UNIT"

#define CONF_HYDROM_NAME "CONF_HYDROM_NAME"
#define CONF_SENSORPERIOD_GRAVITY "CONF_SENSORPERIOD_GRAVITY"
#define CONF_SENSORPERIOD_TEMP "CONF_SENSORPERIOD_TEMP"
#define CONF_SENSORPERIOD_AD "CONF_SENSORPERIOD_AD"
#define CONF_IDLE_TIME_SECONDS "CONF_IDLE_TIME_SECONDS"
#define CONF_LOGLEVEL "CONF_LOGLEVEL"
#define CONF_LANGUAGE "CONF_LANGUAGE"

#define CONF_RESPONSE_BREWBLOX "CONF_RESPONSE_BREWBLOX"
#define CONF_RESPONSE_BREWFATHER "CONF_RESPONSE_BREWFATHER"
#define CONF_RESPONSE_BIERBOT "CONF_RESPONSE_BIERBOT"
#define CONF_RESPONSE_CRAFTBEERPI "CONF_RESPONSE_CRAFTBEERPI"
#define CONF_RESPONSE_FHEM "CONF_RESPONSE_FHEM"
#define CONF_RESPONSE_GRAINFATHER "CONF_RESPONSE_GRAINFATHER"
#define CONF_RESPONSE_HTTP "CONF_RESPONSE_HTTP"
#define CONF_RESPONSE_INFLUXDB "CONF_RESPONSE_INFLUXDB"
#define CONF_RESPONSE_MQTT "CONF_RESPONSE_MQTT"
#define CONF_RESPONSE_PROMETHEUS "CONF_RESPONSE_PROMETHEUS"
#define CONF_RESPONSE_TCONTROL "CONF_RESPONSE_TCONTROL"
#define CONF_RESPONSE_TCP "CONF_RESPONSE_TCP"
#define CONF_RESPONSE_TELEGRAM "CONF_RESPONSE_TELEGRAM"
#define CONF_RESPONSE_THINGSSPEAK "CONF_RESPONSE_THINGSSPEAK"
#define CONF_RESPONSE_UBIDOTS "CONF_RESPONSE_UBIDOTS"
#define CONF_RESPONSE_GOOGLESHEETS "CONF_RESPONSE_GOOGLESHEETS"

#define CONF_RESPONSE_STATUS_BREWBLOX "CONF_RESPONSE_STATUS_BREWBLOX"
#define CONF_RESPONSE_STATUS_BREWFATHER "CONF_RESPONSE_STATUS_BREWFATHER"
#define CONF_RESPONSE_STATUS_BIERBOT "CONF_RESPONSE_STATUS_BIERBOT"
#define CONF_RESPONSE_STATUS_CRAFTBEERPI "CONF_RESPONSE_STATUS_CRAFTBEERPI"
#define CONF_RESPONSE_STATUS_FHEM "CONF_RESPONSE_STATUS_FHEM"
#define CONF_RESPONSE_STATUS_GRAINFATHER "CONF_RESPONSE_STATUS_GRAINFATHER"
#define CONF_RESPONSE_STATUS_HTTP "CONF_RESPONSE_STATUS_HTTP"
#define CONF_RESPONSE_STATUS_INFLUXDB "CONF_RESPONSE_STATUS_INFLUXDB"
#define CONF_RESPONSE_STATUS_MQTT "CONF_RESPONSE_STATUS_MQTT"
#define CONF_RESPONSE_STATUS_PROMETHEUS "CONF_RESPONSE_STATUS_PROMETHEUS"
#define CONF_RESPONSE_STATUS_TCONTROL "CONF_RESPONSE_STATUS_TCONTROL"
#define CONF_RESPONSE_STATUS_TCP "CONF_RESPONSE_STATUS_TCP"
#define CONF_RESPONSE_STATUS_TELEGRAM "CONF_RESPONSE_STATUS_TELEGRAM"
#define CONF_RESPONSE_STATUS_THINGSSPEAK "CONF_RESPONSE_STATUS_THINGSSPEAK"
#define CONF_RESPONSE_STATUS_UBIDOTS "CONF_RESPONSE_STATUS_UBIDOTS"
#define CONF_RESPONSE_STATUS_GOOGLESHEETS "CONF_RESPONSE_STATUS_GOOGLESHEETS"


#define SERIALNR "SERIALNR"
#define CONF_FIRMWAREVERSION "CONF_FIRMWAREVERSION"


#define Ubidots_Server "industrial.api.ubidots.com"

/**
 * GitHub repository used for OTA firmware updates.
 * Format: "owner/repository"  (no leading slash, no .git suffix)
 *
 * The GitHub Actions release pipeline uploads a file named exactly
 * "firmware.bin" as a release asset.  The ArduAutoUpdater finds it
 * via the GitHub Releases API:
 *   GET https://api.github.com/repos/{owner}/{repo}/releases/latest
 *
 * The release tag must match Firmwareversion (e.g. tag "v1.5.7" for "1.5.7").
 *
 */
#define DEF_GITHUB_REPO "TjGer22/Hydrom"

/**
 * Default configuration
*/
#define DEF_MODE MODE_SERVER
#define DEF_IP "192.168.2.1"
#define DEF_GATEWAY "192.168.2.1"
#define DEF_SUBNET "255.255.255.0"

#define DEF_WIFI_SERVER_PASSWORD ""
#define DEF_WIFI_CLIENT_SSID "Bonorum"
#define DEF_WIFI_CLIENT_PASSWORD "WIFI_PASSWORD" 
#define DEF_WIFI_MODE MODE_SERVER
#define DEF_DEVICE_TYPE HYDROM_Latest
#define DEF_DEVICE_LANDINGPAGE 4

#define DEF_DEVICE_Coefficient6 0
#define DEF_DEVICE_Coefficient5 0
#define DEF_DEVICE_Coefficient4 -0.759762391
#define DEF_DEVICE_Coefficient3 11.40801903
#define DEF_DEVICE_Coefficient2 -0.054135111970950
#define DEF_DEVICE_Coefficient1 0.226221075232894
#define DEF_DEVICE_Coefficient0 38.49961125
#define DEF_BLUETOOTH_ENABLE true
#define DEF_BLUETOOTH_UUID 2
#define DEF_BLUETOOTH_BLETRANSPOWER 7
#define DEF_BREWBLOX_ENABLED false
#define DEF_BREWBLOX_SERVER "IP of Brewblox/MQTT broker" 
#define DEF_BREWBLOX_PORT 1883 
#define DEF_BREWBLOX_TOPIC "brewcast/history" 
#define DEF_BREWBLOX_NAME "Hydrom"
#define DEF_BREWBLOX_USER ""
#define DEF_BREWBLOX_PASSWORD ""
#define DEF_BREWFATHER_ENABLED false 
#define DEF_BREWFATHER_SERVER "log.brewfather.net" 
#define DEF_BREWFATHER_URL "/ispindel?id=XXXXXXXXXXX" 
#define DEF_BREWFATHER_PORT 80
#define DEF_BIERBOT_ENABLED false
#define DEF_BIERBOT_SERVER "bricks.bierbot.com" 
#define DEF_BIERBOT_TOKEN "ENTER BIERBOT TOKEN HERE" 
#define DEF_BIERBOT_URL "/api/iot/v1"
#define DEF_CRAFTBEERPI_ENABLED false 
#define DEF_CRAFTBEERPI_SERVER "CRAFTBEERPI_SERVER" 
#define DEF_CRAFTBEERPI_PORT 8000
#define DEF_CRAFTBEERPI_URL "/api/hydrometer/v1/data"
#define DEF_FHEM_ENABLED false 
#define DEF_FHEM_SERVER "FHEM_SERVER"
#define DEF_FHEM_PORT 8083
#define DEF_FHEM_NAME "Hydrom"
#define DEF_GRAINFATHER_ENABLED false
#define DEF_GRAINFATHER_SERVER "community.grainfather.com" 
#define DEF_GRAINFATHER_URL "/iot/XXXX-XXXX/custom" 
#define DEF_GRAINFATHER_PORT 80
#define DEF_HTTP_ENABLED false
#define DEF_HTTP_SERVER "HTTP_SERVER" 
#define DEF_HTTP_URL "HTTP_URL" 
#define DEF_HTTP_PORT 80 
#define DEF_INFLUXDB_ENABLE false 
#define DEF_INFLUXDB_SERVER "INFLUXDB_SERVER" 
#define DEF_INFLUXDB_PORT 8086
#define DEF_INFLUXDB_DB "INFLUXDB_DB" 
#define DEF_INFLUXDB_NAME "INFLUXDB_NAME" 
#define DEF_INFLUXDB_USER "INFLUXDB_USER" 
#define DEF_INFLUXDB_PASSWORT "INFLUXDB_PASSWORT"
#define DEF_INFLUXDB_MEASUREMENTNAME "INFLUXDB_MEASUREMENTNAME"
#define DEF_MQTT_ENABLE false 
#define DEF_MQTT_SERVER "MQTT_SERVER"
#define DEF_MQTT_PORT 1883
#define DEF_MQTT_USER "Username" 
#define DEF_MQTT_PASSWORT "Passwort"
#define DEF_MQTT_TOPICLEVEL "myhome/Garage/Brewery/Fermenter1"
#define DEF_PROMETHEUS_ENABLE false 
#define DEF_PROMETHEUS_SERVER "PROMETHEUS_SERVER" 
#define DEF_PROMETHEUS_PORT 80 
#define DEF_PROMETHEUS_JOB "PROMETHEUS_JOB" 
#define DEF_PROMETHEUS_INSTANCE "PROMETHEUS_INSTANCE" 
#define DEF_TCONTROL_ENABLE false
#define DEF_TCONTROL_SERVER "TCONTROL_SERVER" 
#define DEF_TCONTROL_PORT 80 
#define DEF_TCP_ENABLE false
#define DEF_TCP_SERVER "TCP_SERVER" 
#define DEF_TCP_PORT 9501 
#define DEF_UBIDOTS_ENABLE false
#define DEF_UBIDOTS_TOKEN "UBIDOTS_TOKEN" 
#define DEF_GOOGLESHEETS_ENABLE false
#define DEF_GOOGLESHEETS_TOKEN "GOOGLESHEETS_TOKEN" 
#define DEF_GOOGLESHEETS_SERVER "script.google.com"
#define DEF_GOOGLESHEETS_PORT 443
#define DEF_TELEGRAM_ENABLE false
#define DEF_TELEGRAM_TOKEN "TELEGRAM_TOKEN"
#define DEF_TELEGRAM_CHAT_ID "TELEGRAM_CHAT_ID"
#define DEF_THINGSPEAK_ENABLE false
#define DEF_THINGSPEAK_TOKEN "CONF_THINGSPEAK_TOKEN"
#define DEF_THINGSPEAK_CHANNEL 1
#define DEF_DEEPSLEEP_SECONDS 0 
#define DEF_DEEPSLEEP_MINUTES 15
#define DEF_DEEPSLEEP_HOURS 0
#define DEF_TEMPCOMPENSATION_ENABLED false
#define DEF_TEMPCOMPENSATION_FACTOR 0.013210
#define DEF_RECHEADSTAND_ENABLED false
#define DEF_AUTOFIRMWAREUPDATE_ENABLED false
#define DEF_TEMPERATURE_UNIT C
#define DEF_TILT_UNIT P

#define DEF_DEVICE_ACCELOFFSETX 41
#define DEF_DEVICE_ACCELOFFSETY 42
#define DEF_DEVICE_ACCELOFFSETZ 43

#define MAX_STRING_LENGTH 1024
#define DEF_HYDROM_NAME "INIT_Hydrom"
#define DEF_CONNTIMEOUT 2000
#define DEF_SENSORPERIOD_GRAVITY 20
#define DEF_SENSORPERIOD_TEMP 3
#define DEF_SENSORPERIOD_AD 4
#define DEF_IDLE_TIME_SECONDS 120
#define DEF_LOGLEVEL 0
#define DEF_LANGUAGE 1


/*************************************************************
* DEFS Hydrom
**************************************************************/


#define DEF_LED_GREEN_PIN 5
#define DEF_LED_RED_PIN 4
#define DEF_DS18B20_VCC_PIN 23
#define DEF_DS18B20_DATA_PIN 18
#define DEF_MPU_VCC_PIN 26
#define DEF_SDA_PIN 17
#define DEF_SCL_PIN 16
#define DEF_MPU_Interrupt_PIN 19
#define DEF_MPU_SET_CLOCK 400000
#define DEF_BATTERY_PIN 35
#define DEF_Reset_PIN 27
#define DEF_IDENTIFICATION_PIN_1 32
#define DEF_IDENTIFICATION_PIN_2 33
#define DEF_IDENTIFICATION_PIN_3 34
#define DEF_BatteryScaleFactor 1.527
#define DEF_SHUTDOWN_VOLTAGE 3.0
#define DEF_TIME_SLEEP_FOREVER 10800

#define DEF_LIMIT_LOW_TOLLERANCE_PLATO -1
#define DEF_LIMIT_HIGH_TOLLERANCE_PLATO 1

#define DEF_LIMIT_LOW_TOLLERANCE_TEMPERATURE_DRIFT -0.5
#define DEF_LIMIT_HIGH_TOLLERANCE_TEMPERATURE_DRIFT 0.5

#define DEF_LIMIT_LOW_TOLLERANCE_TEMPERATURE -15
#define DEF_LIMIT_HIGH_TOLLERANCE_TEMPERATURE 26

#define DEF_LIMIT_LOW_TOLLERANCE_GRAVITY 60
#define DEF_LIMIT_HIGH_TOLLERANCE_GRAVITY 78

#define DEF_FILE_SETTINGS "/settings.json"
#define DEF_FILE_SETTINGS_ "/settings_.json"
#define DEF_FILE_OFFSET "/offsets.json"
#define DEF_FILE_SERVICES1 "/services1.json"
#define DEF_FILE_SERVICES2 "/services2.json"
#define DEF_FILE_DEVICEINFO "/Deviceinfo.json"
#define DEF_FILE_SERVICERESPONSE "/ServiceResponse.json"
#define DEF_FILE_FIRMWAREVERSION "/FirmwareVersion.json"
#define DEF_FILE_FONT_WOFF "/Font.woff2"

// ── Button press thresholds (counted in 500 ms ticks) ──────────────────────
static constexpr uint8_t BUTTON_PRESS_RESET_WIFI_SECONDS    = 7;
static constexpr uint8_t BUTTON_PRESS_FACTORY_RESET_SECONDS = 15;

// ── Battery voltage thresholds ─────────────────────────────────────────────
static constexpr float BATTERY_CRITICAL_VOLTAGE = 3.0f;
static constexpr float BATTERY_MIN_VOLTAGE      = 1.0f;

// ── Startup temperature limits (°C) ────────────────────────────────────────
static constexpr float MIN_STARTUP_TEMPERATURE  = 10.0f;
static constexpr float MAX_STARTUP_TEMPERATURE  = 30.0f;

// ── BLE iBeacon ─────────────────────────────────────────────────────────────
static constexpr uint16_t APPLE_IBEACON_MANUFACTURER_ID = 0x4C00;
